name: branteyes_妖言
url: branteyes.github.io
description: 日常学习总结和项目开发记录

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
